"""Protocol bytes, device ids, and frame geometry.

Direct HID framing is shared across the ASUS TUF keyboard family
(OpenRGB AsusAuraTUFKeyboardController.UpdateLeds / RSS_II_RGB DirectProtocol).
"""

from __future__ import annotations

ASUS_VID = 0x0B05
SCOPE_II_RX_PID = 0x1AB5
SCOPE_II_NX_PID = 0x1AB3
SUPPORTED_PIDS = (SCOPE_II_RX_PID, SCOPE_II_NX_PID)

CONTROL_USAGE_PAGE = 0xFF00
CONTROL_USAGE = 0x0001
CONTROL_INTERFACE = 1

LED_COUNT = 107
MATRIX_ROWS = 6
MATRIX_COLS = 24

REPORT_LENGTH = 65  # report-id byte + 64 payload
LEDS_PER_PACKET = 15
PACKETS_PER_FRAME = 8  # ceil(107 / 15)
FRAME_BUFFER_SIZE = PACKETS_PER_FRAME * REPORT_LENGTH

DIRECT_HEADER_HI = 0xC0
DIRECT_HEADER_LO = 0x81

CMD_QUERY = 0x12
QUERY_VERSION = 0x00
QUERY_LAYOUT = 0x12
CMD_EFFECT = 0x51
EFFECT_ARG = 0x2C
EFFECT_COLOR_MODE_SPECIFIC = 0x10
EFFECT_PER_LED_FLAG = 0x02
CMD_SAVE = 0x50
SAVE_ARG = 0x55

DEFAULT_TARGET_FPS = 32
DEVICE_CEILING_FPS = 42
DONE_HOLD_SECONDS = 2.0
DEFAULT_IDLE_WHITE = 0.05
DEFAULT_BRIDGE_PORT = 7420
DEFAULT_BRIDGE_HOST = "127.0.0.1"
MCP_OVERLAY_MAX_SECONDS = 15.0
